services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: collabr
      POSTGRES_PASSWORD: collabrpass
      POSTGRES_DB: collabr_db
    ports:
      - "5432:5432"